### ISSUE TITLE
Error while installing

### ISSUE THREAD

**Issue by linuxwizard** [rperper/lsmcd_cpanel_plugin#1]
Installing cPanel plugins shows below error

Installing LSMCD (LiteSpeed MemcacheD) User Manager...
Verifying requirements...
/usr/local/src/lsmcd_cpanel_plugin/res/lsmcd_usermgr /usr/local/src/lsmcd_cpanel_plugin/res/lsmcd_usermgr
Installs lsmcd if not already installed
lsmcd is already installed
/usr/local/src/lsmcd_cpanel_plugin/res/lsmcd_usermgr/lsmcdsasl.py.raw
Traceback (most recent call last):
  File "./lsmcdsasl.py", line 4, in <module>
    import bmemcached
  File "/usr/lib/python2.7/site-packages/bmemcached/__init__.py", line 3, in <module>
    from bmemcached.client import Client, ReplicatingClient, DistributedClient
  File "/usr/lib/python2.7/site-packages/bmemcached/client/__init__.py", line 4, in <module>
    from .distributed import DistributedClient
  File "/usr/lib/python2.7/site-packages/bmemcached/client/distributed.py", line 2, in <module>
    from uhashring import HashRing
  File "/usr/lib/python2.7/site-packages/uhashring/__init__.py", line 1, in <module>
    from uhashring.ring import HashRing
  File "/usr/lib/python2.7/site-packages/uhashring/ring.py", line 262
    print(f"Numpoints in continuum: {numpoints}")
                                               ^
SyntaxError: invalid syntax
Installing python-binary-memcached
DEPRECATION: Python 2.7 reached the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 is no longer maintained. pip 21.0 will drop support for Python 2.7 in January 2021. More details about Python 2 support in pip can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support pip 21.0 will remove support for this functionality.
Requirement already satisfied: python-binary-memcached in /usr/lib/python2.7/site-packages (0.30.1)
Requirement already satisfied: six in /usr/lib/python2.7/site-packages (from python-binary-memcached) (1.15.0)
Requirement already satisfied: uhashring in /usr/lib/python2.7/site-packages (from python-binary-memcached) (2.0)
Traceback (most recent call last):
  File "./lsmcdsasl.py", line 4, in <module>
    import bmemcached
  File "/usr/lib/python2.7/site-packages/bmemcached/__init__.py", line 3, in <module>
    from bmemcached.client import Client, ReplicatingClient, DistributedClient
  File "/usr/lib/python2.7/site-packages/bmemcached/client/__init__.py", line 4, in <module>
    from .distributed import DistributedClient
  File "/usr/lib/python2.7/site-packages/bmemcached/client/distributed.py", line 2, in <module>
    from uhashring import HashRing
  File "/usr/lib/python2.7/site-packages/uhashring/__init__.py", line 1, in <module>
    from uhashring.ring import HashRing
  File "/usr/lib/python2.7/site-packages/uhashring/ring.py", line 262
    print(f"Numpoints in continuum: {numpoints}")
                                               ^
SyntaxError: invalid syntax
After install, package still missing, check prior messages

**Comment by linuxwizard** [comment]
Hello,

Managed to fix the issue by deleting all unwanted (I believe) "f"'s from the lines below.

 File "/usr/lib/python2.7/site-packages/uhashring/ring.py", line 262
    print(f"Numpoints in continuum: {numpoints}")


 File "/usr/lib/python2.7/site-packages/uhashring/ring_ketama.py", line 35
    w_node_name = f"{node_name}-{w}"

  File "/usr/lib/python2.7/site-packages/uhashring/ring_meta.py", line 33
    self._ring[self.hashi(f"{node_name}-{w}")] = node_name

  File "/usr/lib/python2.7/site-packages/uhashring/ring_meta.py", line 52
    del self._ring[self.hashi(f"{node_name}-{w}")]

I am now able to install the cPanel plugin and everything works well now. I am not a python developer so please review this. If this is correct, there might be a bug with that package.
